"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.GoogleAdsService = void 0;
const google_ads_1 = require("@/lib/google-ads");
exports.GoogleAdsService = {
    publish: async (content) => {
        console.log(`[GoogleAds] Publishing content: ${content.title}`);
        let adCopy = {};
        try {
            // Attempt to parse stringified JSON content generated by AI, or use directly if it is an object
            adCopy = typeof content.content === 'string'
                ? JSON.parse(content.content)
                : content.content;
        }
        catch (e) {
            console.warn(`[GoogleAds] Could not parse content as JSON. Falling back to default format.`);
            adCopy = {
                headlines: [content.title, 'Click Here', 'Learn More'],
                descriptions: [content.content.substring(0, 90) || 'A great offer just for you.', 'Limited time available.']
            };
        }
        // Map AI generated content shape to Google Ads format
        const finalAdData = {
            headlineParts: adCopy.headlines || adCopy.headlineParts || [content.title, 'Special Offer', 'Learn More'],
            descriptionParts: adCopy.descriptions || adCopy.descriptionParts || [
                (content.content || '').substring(0, 90) || 'Check out our latest update.',
                'Exclusive deals available now.'
            ],
            // Google requires a working URL
            finalUrl: adCopy.finalUrl || adCopy.url || 'https://www.homeloans.mx'
        };
        try {
            console.log(`[GoogleAds] Creating Campaign: "Auto-Pilot Campaign - ${new Date().toLocaleDateString()}"`);
            const campaignResult = await (0, google_ads_1.createSearchCampaign)(`Autonomous ${content.title.substring(0, 20)}`);
            if (!campaignResult.success || !campaignResult.campaignResourceName) {
                console.error('[GoogleAds] Campaign creation failed:', campaignResult.error);
                return { success: false, error: campaignResult.error };
            }
            console.log(`[GoogleAds] Creating Ad Group & Ad for Campaign: ${campaignResult.campaignResourceName}`);
            const adResult = await (0, google_ads_1.createAdGroupAndAds)(campaignResult.campaignResourceName, content.title.substring(0, 30), finalAdData);
            if (!adResult.success) {
                console.error('[GoogleAds] Ad Group creation failed:', adResult.error);
                return { success: false, error: adResult.error };
            }
            return {
                success: true,
                platform: "Google Ads",
                campaignId: campaignResult.campaignResourceName,
                adId: adResult.adResourceName,
                status: "LIVE"
            };
        }
        catch (error) {
            console.error('[GoogleAds] Unhandled exception during publishing:', error);
            return { success: false, error: error.message };
        }
    },
    createCampaign: async (name, budget) => {
        const result = await (0, google_ads_1.createSearchCampaign)(name, budget * 1000000); // converting to micros
        return result.success ? result.campaignResourceName : null;
    }
};
